# Generated by Django 3.1 on 2020-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0003_auto_20201004_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='ipv4',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='mcc',
            field=models.CharField(blank=True, default='208', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='mnc',
            field=models.CharField(blank=True, default='93', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='name',
            field=models.CharField(blank=True, default='AMF', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='port',
            field=models.IntegerField(blank=True, default=29518),
        ),
    ]
