# Generated by Django 3.1 on 2020-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0004_auto_20201004_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='ipv4',
            field=models.CharField(default='127.0.0.1', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='mcc',
            field=models.CharField(default='208', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='name',
            field=models.CharField(default='AMF', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='port',
            field=models.IntegerField(default=29518),
        ),
    ]
