# Generated by Django 3.1 on 2020-10-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0005_auto_20201004_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='mnc',
            field=models.CharField(default='93', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='name',
            field=models.CharField(default='AMF', max_length=20, null=True),
        ),
    ]
