# Generated by Django 3.1 on 2020-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0006_auto_20201004_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='name',
            field=models.CharField(default='AMF', max_length=20),
        ),
    ]
