# Generated by Django 3.1 on 2020-10-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0010_auto_20201004_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
