# Generated by Django 3.1 on 2020-10-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0012_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
