# Generated by Django 3.1 on 2020-10-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0013_auto_20201009_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amfmodel',
            old_name='name',
            new_name='amfName',
        ),
        migrations.RenameField(
            model_name='amfmodel',
            old_name='ipv4',
            new_name='ipv4Addr',
        ),
    ]
