# Generated by Django 3.1 on 2020-10-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0014_auto_20201011_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
