# Generated by Django 3.1 on 2020-10-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0015_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunScenariosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=20)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
