# Generated by Django 3.1 on 2020-10-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0016_runscenariosmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runscenariosmodel',
            name='name',
            field=models.CharField(default='green', max_length=20),
        ),
    ]
