# Generated by Django 3.1 on 2020-10-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0017_auto_20201011_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='runscenariosmodel',
            name='nameInScript',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='runscenariosmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
