# Generated by Django 3.1 on 2020-10-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0018_auto_20201011_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runscenariosmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='runscenariosmodel',
            name='nameInScript',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
