# Generated by Django 3.1 on 2020-10-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0019_auto_20201014_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amfmodel',
            options={'verbose_name': 'AMF Config', 'verbose_name_plural': 'AMF Config'},
        ),
        migrations.AlterModelOptions(
            name='runscenariosmodel',
            options={'verbose_name': 'Scenario', 'verbose_name_plural': 'Scenarios'},
        ),
    ]
