# Generated by Django 3.1 on 2020-10-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0020_auto_20201014_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amfmodel',
            old_name='ipv4Addr',
            new_name='ngapIpList',
        ),
        migrations.RenameField(
            model_name='amfmodel',
            old_name='port',
            new_name='non3gppDeregistrationTimer',
        ),
        migrations.RenameField(
            model_name='amfmodel',
            old_name='mcc',
            new_name='plmnSupportList_plmnId_mcc',
        ),
        migrations.RenameField(
            model_name='amfmodel',
            old_name='mnc',
            new_name='plmnSupportList_plmnId_mnc',
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='networkName_full',
            field=models.CharField(blank=True, default='fiveGbackpack', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='networkName_short',
            field=models.CharField(blank=True, default='fiveGbp', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='nrfUri',
            field=models.CharField(blank=True, default='http://localhost:29510', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='plmnSupportList_snssaiList_sst',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='sbi_port',
            field=models.IntegerField(blank=True, default=29518),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='sbi_registerIPv4',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='sbi_scheme',
            field=models.CharField(blank=True, default='http', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='security_cipheringOrder',
            field=models.CharField(blank=True, default='NEA0', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='security_integrityOrder',
            field=models.CharField(blank=True, default='NIA2', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='servedGuamiList_amfId',
            field=models.CharField(blank=True, default='cafe00', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='servedGuamiList_plmnId_mcc',
            field=models.CharField(blank=True, default='208', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='servedGuamiList_plmnId_mnc',
            field=models.CharField(blank=True, default='93', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='serviceNameList',
            field=models.CharField(blank=True, default='[namf-comm, namf-evts, ...]', max_length=100),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='supportDnnList',
            field=models.CharField(blank=True, default='internet', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='supportTaiList_plmnId_mcc',
            field=models.CharField(blank=True, default='208', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='supportTaiList_plmnId_mnc',
            field=models.CharField(blank=True, default='93', max_length=20),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='supportTaiList_tac',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='t3502',
            field=models.IntegerField(blank=True, default=29518),
        ),
        migrations.AddField(
            model_name='amfmodel',
            name='t3512',
            field=models.IntegerField(blank=True, default=29518),
        ),
    ]
