# Generated by Django 3.1 on 2020-10-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0021_auto_20201101_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='plmnSupportList_snssaiList_sst',
            field=models.CharField(blank=True, default='[1-010203, 1-112233]', max_length=20),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='t3502',
            field=models.IntegerField(blank=True, default=720),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='t3512',
            field=models.IntegerField(blank=True, default=3600),
        ),
    ]
