# Generated by Django 3.1 on 2020-10-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0022_auto_20201101_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='nrfUri',
            field=models.CharField(blank=True, default='http://localhost:29510', max_length=50),
        ),
    ]
