# Generated by Django 3.1 on 2020-10-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0023_auto_20201101_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='amfName',
            field=models.CharField(blank=True, default='AMF', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='networkName_full',
            field=models.CharField(blank=True, default='fiveGbackpack', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='networkName_short',
            field=models.CharField(blank=True, default='fiveGbp', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='ngapIpList',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='plmnSupportList_plmnId_mcc',
            field=models.CharField(blank=True, default='208', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='plmnSupportList_plmnId_mnc',
            field=models.CharField(blank=True, default='93', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='plmnSupportList_snssaiList_sst',
            field=models.CharField(blank=True, default='[1-010203, 1-112233]', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='sbi_registerIPv4',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='sbi_scheme',
            field=models.CharField(blank=True, default='http', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='security_cipheringOrder',
            field=models.CharField(blank=True, default='NEA0', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='security_integrityOrder',
            field=models.CharField(blank=True, default='NIA2', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='servedGuamiList_amfId',
            field=models.CharField(blank=True, default='cafe00', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='servedGuamiList_plmnId_mcc',
            field=models.CharField(blank=True, default='208', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='servedGuamiList_plmnId_mnc',
            field=models.CharField(blank=True, default='93', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='supportDnnList',
            field=models.CharField(blank=True, default='internet', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='supportTaiList_plmnId_mcc',
            field=models.CharField(blank=True, default='208', max_length=50),
        ),
        migrations.AlterField(
            model_name='amfmodel',
            name='supportTaiList_plmnId_mnc',
            field=models.CharField(blank=True, default='93', max_length=50),
        ),
    ]
