# Generated by Django 3.1 on 2020-10-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0024_auto_20201101_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='plmnSupportList_snssaiList_sst',
            field=models.CharField(blank=True, default='[{sst:1, sd:010203}, {sst:1, sd:112233}]', max_length=50),
        ),
    ]
