# Generated by Django 3.1 on 2020-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0025_auto_20201101_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfmodel',
            name='serviceNameList',
            field=models.CharField(blank=True, default='[namf-comm, namf-evts, namf-mt, namf-loc, namf-oam]', max_length=100),
        ),
    ]
