# Generated by Django 3.1 on 2020-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0026_auto_20201101_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='smfModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('smfName', models.CharField(blank=True, default='SMF', max_length=50)),
                ('sbi_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('sbi_registerIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_bindingIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_port', models.CharField(blank=True, default='29502', max_length=50)),
                ('sbi_tls_key', models.CharField(blank=True, default='free5gc/support/TLS/smf.key', max_length=50)),
                ('sbi_tls_pem', models.CharField(blank=True, default='free5gc/support/TLS/smf.pem', max_length=50)),
                ('nrfUri', models.CharField(blank=True, default='http://localhost:29510', max_length=50)),
                ('serviceNameList', models.CharField(blank=True, default='[nsmf-pdusession, nsmf-event-exposure, nsmf-oam]', max_length=100)),
                ('snssai_info_sNssai', models.CharField(blank=True, default='{sst:1, sd:010203}', max_length=50)),
                ('snssai_info_dnnSmfInfoList', models.CharField(blank=True, default='internet', max_length=50)),
                ('userplane_information_up_nodes_gNB1_type', models.CharField(blank=True, default='AN', max_length=50)),
                ('userplane_information_up_nodes_gNB1_an_ip', models.CharField(blank=True, default='127.0.0.100', max_length=50)),
                ('userplane_information_up_nodes_UPF_type', models.CharField(blank=True, default='UPF', max_length=50)),
                ('userplane_information_up_nodes_UPF_node_id', models.CharField(blank=True, default='127.0.0.8', max_length=50)),
                ('userplane_information_links_A', models.CharField(blank=True, default='gNB1', max_length=50)),
                ('userplane_information_links_B', models.CharField(blank=True, default='UPF', max_length=50)),
                ('pfcp_addr', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('pfcp_ue_subnet', models.CharField(blank=True, default='60.60.0.0/16', max_length=50)),
                ('dnn', models.CharField(blank=True, default='[dnn:internet, dns:{ipv4:8.8.8.8, ipv6:2001:4860:4860::8888}]', max_length=200)),
            ],
        ),
    ]
