# Generated by Django 3.1 on 2020-11-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0029_auto_20201102_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ausfModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ausfName', models.CharField(blank=True, default='AUSF', max_length=50)),
                ('sbi_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('sbi_registerIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_bindingIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_port', models.IntegerField(blank=True, default=29509)),
                ('nrfUri', models.CharField(blank=True, default='http://localhost:29510', max_length=50)),
                ('serviceNameList', models.CharField(blank=True, default='[nausf-auth]', max_length=100)),
                ('plmnSupportList', models.CharField(blank=True, default='{mcc: 208, mnc: 93}', max_length=100)),
                ('groupId', models.CharField(blank=True, default='ausfGroup001', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='smfmodel',
            name='dnn_dns',
            field=models.CharField(blank=True, default='{ipv4:8.8.8.8, ipv6:2001:4860:4860::8888}', max_length=200),
        ),
    ]
