# Generated by Django 3.1 on 2020-11-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0030_auto_20201103_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='nrfModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nrfName', models.CharField(blank=True, default='NRF', max_length=50)),
                ('MongoDBName', models.CharField(blank=True, default='free5gc', max_length=50)),
                ('MongoDBUrl', models.CharField(blank=True, default='mongodb://127.0.0.1:27017', max_length=50)),
                ('DefaultServiceIP', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('sbi_ipv4Addr', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_port', models.CharField(blank=True, default='29510', max_length=50)),
                ('DefaultPlmnId', models.CharField(blank=True, default='{mcc: 208, mnc: 93}', max_length=50)),
                ('serviceNameList', models.CharField(blank=True, default='[nnrf-nfm, nnrf-disc]', max_length=50)),
            ],
            options={
                'verbose_name': 'NRF Config',
                'verbose_name_plural': 'NRF Config',
            },
        ),
        migrations.AlterModelOptions(
            name='ausfmodel',
            options={'verbose_name': 'AUSF Config', 'verbose_name_plural': 'AUSF Config'},
        ),
    ]
