# Generated by Django 3.1 on 2020-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0031_auto_20201103_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcfModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pcfName', models.CharField(blank=True, default='PCF', max_length=50)),
                ('defaultBdtRefId', models.CharField(blank=True, default='BdtPolicyId-', max_length=50)),
                ('timeFormat', models.CharField(blank=True, default='2019-01-02 15:04:05', max_length=50)),
                ('sbi_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('sbi_registerIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_bindingIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_port', models.CharField(blank=True, default='29507', max_length=50)),
                ('nrfUri', models.CharField(blank=True, default='http://localhost:29510', max_length=100)),
                ('serviceList_serviceName', models.CharField(blank=True, default='[npcf-am-policy-control, npcf-smpolicycontrol, npcf-bdtpolicycontrol, npcf-policyauthorization, npcf-eventexposure, npcf-ue-policy-control]', max_length=300)),
                ('serviceList_suppFeat', models.CharField(blank=True, default='[3fff, 3]', max_length=300)),
            ],
            options={
                'verbose_name': 'PCF Config',
                'verbose_name_plural': 'PCF Config',
            },
        ),
    ]
