# Generated by Django 3.1 on 2020-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0032_pcfmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcfExtraServiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraServiceID', models.IntegerField()),
                ('extraServiceName', models.CharField(blank=True, max_length=300)),
                ('serviceList_serviceName', models.CharField(blank=True, max_length=300)),
                ('serviceList_suppFeat', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='pcfmodel',
            name='serviceList_serviceName',
            field=models.CharField(blank=True, default='npcf-am-policy-control', max_length=300),
        ),
        migrations.AlterField(
            model_name='pcfmodel',
            name='serviceList_suppFeat',
            field=models.CharField(blank=True, default='3fff', max_length=300),
        ),
    ]
