# Generated by Django 3.1 on 2020-11-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0033_auto_20201103_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcfextraservicemodel',
            options={'verbose_name': 'PCF Extra Service', 'verbose_name_plural': 'PCF Extra Service'},
        ),
        migrations.AddField(
            model_name='pcfextraservicemodel',
            name='default',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
