# Generated by Django 3.1 on 2020-11-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0034_auto_20201103_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcfextraservicemodel',
            name='default',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pcfextraservicemodel',
            name='extraServiceName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pcfextraservicemodel',
            name='serviceList_serviceName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pcfextraservicemodel',
            name='serviceList_suppFeat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
