# Generated by Django 3.1 on 2020-11-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0035_auto_20201103_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcfmodel',
            name='serviceList_suppFeat',
            field=models.CharField(blank=True, default='3fff', max_length=300, null=True),
        ),
    ]
