# Generated by Django 3.1 on 2020-11-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0036_auto_20201103_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='udmModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('udmName', models.CharField(blank=True, default='UDM', max_length=50)),
                ('sbi_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('sbi_registerIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_bindingIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_port', models.CharField(blank=True, default='29503', max_length=50)),
                ('nrfUri', models.CharField(blank=True, default='http://localhost:29510', max_length=50)),
                ('udrclient_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('udrclient_ipv4Addr', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('udrclient_port', models.CharField(blank=True, default='29504', max_length=50)),
                ('nrfclient_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('nrfclient_ipv4Addr', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('nrfclient_port', models.CharField(blank=True, default='29510', max_length=50)),
                ('serviceNameList', models.CharField(blank=True, default='[nudm-sdm, nudm-uecm, nudm-ueau, nudm-ee, nudm-pp]', max_length=200)),
            ],
            options={
                'verbose_name': 'UDM Config',
                'verbose_name_plural': 'UDM Config',
            },
        ),
    ]
