# Generated by Django 3.1 on 2020-11-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0037_udmmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='udrModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('udrName', models.CharField(blank=True, default='UDR', max_length=50)),
                ('sbi_scheme', models.CharField(blank=True, default='http', max_length=50)),
                ('sbi_registerIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_bindingIPv4', models.CharField(blank=True, default='127.0.0.1', max_length=50)),
                ('sbi_port', models.CharField(blank=True, default='29504', max_length=50)),
                ('nrfUri', models.CharField(blank=True, default='http://localhost:29510', max_length=50)),
                ('mongodb_name', models.CharField(blank=True, default='free5gc', max_length=50)),
                ('mongodb_url', models.CharField(blank=True, default='mongodb://localhost:27017', max_length=200)),
            ],
            options={
                'verbose_name': 'UDR Config',
                'verbose_name_plural': 'UDR Config',
            },
        ),
    ]
