# Generated by Django 3.1.3 on 2020-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0039_auto_20201122_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upfmodel',
            name='dnn_list',
            field=models.CharField(blank=True, default='[{"dnn":"internet", "cidr":"60.60.0.0/24"}]', max_length=600),
        ),
        migrations.AlterField(
            model_name='upfmodel',
            name='gtpu',
            field=models.CharField(blank=True, default='[{"addr": "10.200.200.102"}]', max_length=600),
        ),
        migrations.AlterField(
            model_name='upfmodel',
            name='pfcp',
            field=models.CharField(blank=True, default='[{"addr": "10.200.200.101"}]', max_length=600),
        ),
    ]
