# Generated by Django 3.1.3 on 2020-11-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiveGApp', '0040_auto_20201124_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amfModel',
        ),
        migrations.DeleteModel(
            name='ausfModel',
        ),
        migrations.DeleteModel(
            name='nrfModel',
        ),
        migrations.DeleteModel(
            name='nssfModel',
        ),
        migrations.DeleteModel(
            name='pcfExtraServiceModel',
        ),
        migrations.DeleteModel(
            name='pcfModel',
        ),
        migrations.DeleteModel(
            name='smfModel',
        ),
        migrations.DeleteModel(
            name='udmModel',
        ),
        migrations.DeleteModel(
            name='udrModel',
        ),
        migrations.DeleteModel(
            name='upfModel',
        ),
    ]
