# Generated by Django 3.1 on 2020-10-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedtracesmodel',
            options={'verbose_name': 'Generated Trace', 'verbose_name_plural': 'Generated Traces'},
        ),
    ]
